
services:
  postgre:
    image: postgres:14.5
    command: postgres -c 'max_connections=200'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "ErshAdmin"
      POSTGRES_DB: "Ersh"
      POSTGRES_PASSWORD: "ErshPassword"